version: 2
jobs:
  build:
    working_directory: ~/bootlaces
    docker:
      - image: clojure:boot-2.7.2
    steps:
      - checkout
      - restore_cache:
          key: bootlaces-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot check
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              boot publish
            fi
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: bootlaces-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
      BOOT_WATCHERS_DISABLE: "yes"
